#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$ROOT_DIR"

# Base configuration (requested)
SPLIT_MODE="source"
SPLIT_RATIO="0.7,0.15,0.15"
NUM_STREAMS="100000"
EVENTS_PER_STREAM="120"
MIN_CONFIDENCE="medium"
DECISION_STRIDE="8"
TABULAR_EPISODES="10000"
DEEP_EPISODES="10000"
EVAL_EPISODES="100"
INTRA_RUN_BENIGN_PROB="0.05"
ATTACK_RUNS_MAX="3"

# Group tactic sets
GROUP1_TACTICS="Execution,Discovery,Defense Evasion,Command and Control,AutomatedTestingTools"
GROUP2_TACTICS="Credential Access,Privilege Escalation"
GROUP3_TACTICS="Persistence,Lateral Movement"
GROUP4_TACTICS="Other"

# Representative one-per-group (Other excluded)
# Execution / Credential Access / Persistence
REP_TACTICS="Execution,Credential Access,Persistence"
CHECKPOINT_INDEX="results/group5_runs/checkpoint_paths.txt"
EVAL_HISTORY_INDEX="results/group5_runs/eval_history_paths.txt"
PLOT_AFTER_EACH_RUN="false"

run_one() {
  local run_name="$1"
  local tactics="$2"
  local out_dir="results/group5_runs/${run_name}"
  local ckpt_dir="${out_dir}/checkpoints"
  local eval_hist_dir="${out_dir}/eval_history"
  local plot_dir="${out_dir}/plots"
  echo ""
  echo "============================================================"
  echo "[RUN] ${run_name}"
  echo "[TACTICS] ${tactics}"
  echo "============================================================"

  ./run_all_compare_runs.sh \
    --split-mode "$SPLIT_MODE" \
    --split-ratio "$SPLIT_RATIO" \
    --num-streams "$NUM_STREAMS" \
    --events-per-stream "$EVENTS_PER_STREAM" \
    --min-confidence "$MIN_CONFIDENCE" \
    --decision-stride "$DECISION_STRIDE" \
    --tabular-episodes "$TABULAR_EPISODES" \
    --deep-episodes "$DEEP_EPISODES" \
    --eval-episodes "$EVAL_EPISODES" \
    --intra-run-benign-prob "$INTRA_RUN_BENIGN_PROB" \
    --attack-runs-max "$ATTACK_RUNS_MAX" \
    --use-tactics "$tactics" \
    --output-dir "$out_dir"

  echo "[CHECKPOINTS] ${ckpt_dir}"
  echo "  - ${ckpt_dir}/stream_dqn.pt"
  echo "  - ${ckpt_dir}/stream_reinforce.pt"
  echo "  - ${ckpt_dir}/stream_a2c.pt"
  echo "[EVAL_HISTORY] ${eval_hist_dir}"
  echo "  - ${eval_hist_dir}/stream_dqn_eval_history.jsonl"
  echo "  - ${eval_hist_dir}/stream_reinforce_eval_history.jsonl"
  echo "  - ${eval_hist_dir}/stream_a2c_eval_history.jsonl"
  {
    echo "[${run_name}]"
    echo "output_dir=${out_dir}"
    echo "checkpoints_dir=${ckpt_dir}"
    echo "stream_dqn_pt=${ckpt_dir}/stream_dqn.pt"
    echo "stream_reinforce_pt=${ckpt_dir}/stream_reinforce.pt"
    echo "stream_a2c_pt=${ckpt_dir}/stream_a2c.pt"
    echo ""
  } >> "$CHECKPOINT_INDEX"

  {
    echo "[${run_name}]"
    echo "output_dir=${out_dir}"
    echo "eval_history_dir=${eval_hist_dir}"
    echo "stream_dqn_eval_history=${eval_hist_dir}/stream_dqn_eval_history.jsonl"
    echo "stream_reinforce_eval_history=${eval_hist_dir}/stream_reinforce_eval_history.jsonl"
    echo "stream_a2c_eval_history=${eval_hist_dir}/stream_a2c_eval_history.jsonl"
    echo ""
  } >> "$EVAL_HISTORY_INDEX"

  if [[ "$PLOT_AFTER_EACH_RUN" == "true" ]]; then
    python -m threat_agent.plot_eval_history \
      --eval-history-dir "$eval_hist_dir" \
      --output-dir "$plot_dir" || true
    echo "[PLOTS] ${plot_dir}"
  fi
}

mkdir -p "results/group5_runs"
cat > "$CHECKPOINT_INDEX" <<'EOF'
# Group5 run checkpoint paths
#
# This file is auto-generated by run_all_compare_runs_group5.sh
EOF

cat > "$EVAL_HISTORY_INDEX" <<'EOF'
# Group5 run eval_history paths
#
# This file is auto-generated by run_all_compare_runs_group5.sh
EOF

# 1) Four group runs
run_one "group1_execution_recon_evasion" "$GROUP1_TACTICS"
run_one "group2_credential_privilege" "$GROUP2_TACTICS"
run_one "group3_persistence_lateral" "$GROUP3_TACTICS"
run_one "group4_residual_other" "$GROUP4_TACTICS"

# 2) Representative mixed run (excluding Other)
run_one "group5_representative_mix" "$REP_TACTICS"

echo ""
echo "All 5 grouped runs completed."
echo "Output root: results/group5_runs"
echo "Checkpoint index: ${CHECKPOINT_INDEX}"
echo "Eval history index: ${EVAL_HISTORY_INDEX}"

